language: java
os: linux
env:
  global:
    - CASSANDRA_HOST=127.0.0.1
    - CASSANDRA_PORT=9042

sudo: required

jdk:
  - oraclejdk8

services:
  - cassandra

script: mvn clean install cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
